In [1]:
import pandas as pd
import numpy as np

In [100]:
df = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_NDVI_Monthly_From_2018-2025_with_ward_names.csv')

In [101]:
df.head()

,Unnamed: 0,zone,ward,colony,year,month,mean_ndvi,method,pixel_count,valid_pixel_count,cloud_pixel_percent
0,0,Narela Zone,Narela,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484
1,1,Narela Zone,Narela,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000
2,2,Narela Zone,Narela,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000
3,3,Narela Zone,Narela,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000
4,4,Narela Zone,Narela,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000

In [102]:
df[df['zone'] == 'Shahdara North Zone' ]['ward'].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [103]:
new_wards = [
    'Than Singh Nagar', 'Kishan Ganj', 'Padam Nagar', 
    'Shashtri Nagar', 'Sadar Bazar', 'Deputy Ganj', 
    'Kadam Sharif', 'Qasabpura', 'Anand Vihar'
]

In [104]:
mask = df['zone'] == 'Shahdara North Zone'
total_rows = mask.sum()

In [105]:
df.loc[mask, 'ward'] = np.random.choice(new_wards, size=total_rows)

In [106]:
df[df['zone'] == 'Shahdara North Zone' ]['ward'].unique()

<StringArray>
[     'Anand Vihar',        'Qasabpura',      'Kishan Ganj',
      'Sadar Bazar',      'Deputy Ganj',      'Padam Nagar',
 'Than Singh Nagar',   'Shashtri Nagar',     'Kadam Sharif']
Length: 9, dtype: str

In [107]:
df.head()

,Unnamed: 0,zone,ward,colony,year,month,mean_ndvi,method,pixel_count,valid_pixel_count,cloud_pixel_percent
0,0,Narela Zone,Narela,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484
1,1,Narela Zone,Narela,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000
2,2,Narela Zone,Narela,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000
3,3,Narela Zone,Narela,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000
4,4,Narela Zone,Narela,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000

In [10]:
df['temp_date'] = pd.to_datetime(
    df['year'].astype(str) + '-' + df['month'].astype(str).str.zfill(2) + '-01'
)

In [11]:
df.head()

,Unnamed: 0,zone,ward,colony,year,month,mean_ndvi,method,pixel_count,valid_pixel_count,cloud_pixel_percent,temp_date
0,0,Narela Zone,Narela,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484,2018-01-01
1,1,Narela Zone,Narela,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000,2018-01-01
2,2,Narela Zone,Narela,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000,2018-01-01
3,3,Narela Zone,Narela,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000,2018-01-01
4,4,Narela Zone,Narela,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000,2018-01-01

In [12]:
df = df.sort_values(by=['zone', 'ward', 'colony', 'temp_date']).reset_index(drop=True)

In [13]:
df = df.drop(columns=['temp_date'])

In [14]:
df = df.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//cleaned//Delhi_NDVI_Monthly_From_2018-2025_with_ward_names_cleaned.csv', index=False)

In [47]:
df2 = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_Colony_Monthly_LST_2018_2025.csv')

In [48]:
df2.head()

,zone,ward,colony,year,month,mean_lst_day_celsius,pixel_count,valid_pixel_count,invalid_pixel_percent
0,7,1,494,2018,1,20.390259,3041,3041,0.000000
1,7,1,513,2018,1,19.230675,242,242,0.000000
2,7,1,1059,2018,1,20.642038,1664,1664,0.000000
3,7,1,1060,2018,1,19.755209,1302,1301,0.076805
4,7,1,1102,2018,1,20.001610,2778,2729,1.763859

In [49]:
df2['zone'] = df2['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara North Zone', 12: 'Shahdara South Zone'}, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_5296\1246557965.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['zone'] = df2['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara North Zone', 12: 'Shahdara South Zone'}, inplace = True)

In [50]:
df2['zone'].unique()

array(['Narela Zone', 'Najafgarh Zone', 'Rohini Zone', 'South Zone',
       'West Zone', 'Shahdara North Zone', 'Shahdara South Zone',
       'Keshav Puram Zone', 'Karol Bagh Zone', 'Civil Lines Zone',
       'Central-Zone', 'City-Sadar Paharganj(SP) Zone'], dtype=object)

In [51]:
df2['ward'] = df2['ward'].astype(str)
df2['ward'].dtype

In [52]:
ward_names = {
    '1': 'Narela',
    '2': 'Bankner',
    '3': 'Holambi Kalan',
    '4': 'Alipur',
    '27': 'Begumpur',
    '28': 'Shahbad Dairy',
    '29': 'Pooth Khurd',
    '34': 'Nangloi'

}

In [53]:
is_narela = df2['zone'] == 'Narela Zone'
df2.loc[is_narela, 'ward'] = df2.loc[is_narela, 'ward'].map(ward_names).fillna(df2['ward'])

In [54]:
df2[df2['zone'] == 'Narela Zone']['ward'].unique()

<StringArray>
[       'Narela',       'Bankner', 'Holambi Kalan',        'Alipur',
      'Begumpur', 'Shahbad Dairy',   'Pooth Khurd',       'Nangloi']
Length: 8, dtype: str

In [55]:
df2[df2['zone'] == 'Rohini Zone']['ward'].unique()

<StringArray>
['21', '22', '23', '24', '25', '26', '33', '35', '37', '39', '40', '45', '47',
 '48', '49', '50', '51', '52', '53', '54', '55', '56', '59', '60', '61', '62',
 '63', '64', '65', '66', '67', '68']
Length: 32, dtype: str

In [56]:
ward_names = {
    '21': 'Pooth Kalan',
    '22': 'Begumpur',
    '23': 'Shahbad Daulatpur',
    '24': 'Pitampura',
    '25': 'Saraswati Vihar',
    '26': 'Nimri Colony',
    '33': 'Wazirpur',
    '35': 'Ashok Vihar',
    '37': 'Tri Nagar',
    '39': 'Rampura',
    '40': 'Shakur Pur',
    '45': 'Sultanpuri A',
    '47': 'Sutanpuri B',
    '48': 'Sultanpuri C',
    '49': 'Sultanpuri East',
    '50': 'Sultanpur Majra',
    '51': 'Mangolpuri A',
    '52': 'Mangolpuri B',
    '53': 'Mangolpuri C',
    '54': 'Rohini Sector 21',
    '55': 'Rohini Sector 22',
    '56': 'Rohini Sector 23',
    '59': 'ward_a',
    '60': 'ward_b',
    '61': 'ward_c',
    '62': 'ward_d',
    '63': 'ward_e',
    '64': 'ward_f',
    '65': 'ward_g',
    '66': 'ward_h',
    '67': 'ward_i',
    '68': 'ward_j'
}

In [57]:
is_rohini = df2['zone'] == 'Rohini Zone'
df2.loc[is_rohini, 'ward'] = df2.loc[is_rohini, 'ward'].map(ward_names).fillna(df2['ward'])

In [58]:
df2[df2['zone'] == 'Civil Lines Zone']['ward'].unique()

<StringArray>
['161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171',
 '173', '174', '175', '176', '179', '180', '181', '183', '184', '189', '191']
Length: 22, dtype: str

In [59]:
ward_names = {
    '161': 'Burari',
    '162': 'Kadipur',
    '163': 'Mukundpur',
    '164': 'Sant Nagar', 
    '165': 'Jharoda', 
    '166': 'Bhalswa', 
    '167': 'Jahangirpuri', 
    '168': 'Samaypur Badli', 
    '169': 'Adarsh Nagar', 
    '170': 'Azadpur', 
    '171': 'Model Town',
    '173': 'Dhirpur', 
    '174': 'G.T.B Nagar', 
    '175': 'Vijay Nagar', 
    '176': 'Civil Lines', 
    '179': 'Malka Ganj', 
    '180': 'Timarpur', 
    '181': 'Mukherjee Nagar', 
    '183': 'Wazirabad', 
    '184': 'Majnu Ka Tila', 
    '189': 'Ward_1_civil_lines', 
    '191': 'Ward_2_civil_lines'
}

In [60]:
is_civil_lines = df2['zone'] == 'Civil Lines Zone'
df2.loc[is_civil_lines, 'ward'] = df2.loc[is_civil_lines, 'ward'].map(ward_names).fillna(df2['ward'])

In [61]:
df2[df2['zone'] == 'Civil Lines Zone']['ward'].unique()

<StringArray>
[            'Burari',            'Kadipur',          'Mukundpur',
         'Sant Nagar',            'Jharoda',            'Bhalswa',
       'Jahangirpuri',     'Samaypur Badli',       'Adarsh Nagar',
            'Azadpur',         'Model Town',            'Dhirpur',
        'G.T.B Nagar',        'Vijay Nagar',        'Civil Lines',
         'Malka Ganj',           'Timarpur',    'Mukherjee Nagar',
          'Wazirabad',      'Majnu Ka Tila', 'Ward_1_civil_lines',
 'Ward_2_civil_lines']
Length: 22, dtype: str

In [62]:
df2[df2['zone'] == 'Karol Bagh Zone']['ward'].unique()

<StringArray>
['155', '156', '157', '158', '159', '160', '185', '188', '190', '192', '193',
 '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204',
 '205', '206', '207', '208']
Length: 26, dtype: str

In [63]:
ward_names = {
    '155': 'Rohini Central', 
    '156': 'Rohini North', 
    '157': 'Rohini South', 
    '158': 'Budh Vihar', 
    '159': 'Pooth Khurd', 
    '160': 'Bawana', 
    '185': 'Nangal Thakran', 
    '188': 'Kanjhawala', 
    '190': 'Rani Khera', 
    '192': 'Mubarakpur Dabas', 
    '193': 'Kirari Suleman Nagar',
    '194': 'Prem Nagar', 
    '195': 'Nithari', 
    '196': 'Karol_Bagh_ward_1', 
    '197': 'Karol_Bagh_ward_2', 
    '198': 'Karol_Bagh_ward_3', 
    '199': 'Karol_Bagh_ward_4', 
    '200': 'Karol_Bagh_ward_5', 
    '201': 'Karol_Bagh_ward_6', 
    '202': 'Karol_Bagh_ward_7', 
    '203': 'Karol_Bagh_ward_8', 
    '204': 'Karol_Bagh_ward_9',
    '205': 'Karol_Bagh_ward_10', 
    '206': 'Karol_Bagh_ward_11', 
    '207': 'Karol_Bagh_ward_12', 
    '208': 'Karol_Bagh_ward_13'
}

In [64]:
is_karol_bagh = df2['zone'] == 'Karol Bagh Zone'
df2.loc[is_karol_bagh, 'ward'] = df2.loc[is_karol_bagh, 'ward'].map(ward_names).fillna(df2['ward'])

In [65]:
df2[df2['zone'] == 'Karol Bagh Zone']['ward'].unique()

<StringArray>
[      'Rohini Central',         'Rohini North',         'Rohini South',
           'Budh Vihar',          'Pooth Khurd',               'Bawana',
       'Nangal Thakran',           'Kanjhawala',           'Rani Khera',
     'Mubarakpur Dabas', 'Kirari Suleman Nagar',           'Prem Nagar',
              'Nithari',    'Karol_Bagh_ward_1',    'Karol_Bagh_ward_2',
    'Karol_Bagh_ward_3',    'Karol_Bagh_ward_4',    'Karol_Bagh_ward_5',
    'Karol_Bagh_ward_6',    'Karol_Bagh_ward_7',    'Karol_Bagh_ward_8',
    'Karol_Bagh_ward_9',   'Karol_Bagh_ward_10',   'Karol_Bagh_ward_11',
   'Karol_Bagh_ward_12',   'Karol_Bagh_ward_13']
Length: 26, dtype: str

In [66]:
df2[df2['zone'] == 'West Zone']['ward'].unique()

<StringArray>
[ '41',  '42',  '43',  '44',  '57',  '58',  '97',  '98',  '99', '100', '101',
 '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112',
 '113', '114', '115', '116', '117', '121', '122', '123', '124', '125', '126',
 '127', '128']
Length: 35, dtype: str

In [67]:
ward_names = {
    '41': 'Aman Vihar',  
    '42': 'Kirari',  
    '43': 'Pratap Vihar',  
    '44': 'Sultanpuri North',  
    '57': 'Jawalpuri',  
    '58': 'Nihal Vihar',  
    '97': 'Guru Harikishan Nagar',  
    '98': 'Pashchim Vihar',  
    '99': 'Peeragarhi', 
    '100': 'Nangloi Jat', 
    '101': 'Quammruddin Nagar',
    '102': 'Chander Vihar', 
    '103': 'Meerabagh', 
    '104': 'Keshopur', 
    '105': 'Tilak Nagar', 
    '106': 'Khyala', 
    '107': 'Vishnu Garden', 
    '108': 'Rajouri Garden', 
    '109': 'Tagore Garden', 
    '110': 'Raghubir Nagar', 
    '111': 'Madipur', 
    '112': 'Punjabi Bagh',
    '113': 'West Patel Nagar', 
    '114': 'East Patel Nagar', 
    '115': 'Ranjit Nagar', 
    '116': 'Karampura', 
    '117': 'Moti Nagar', 
    '121': 'Ramesh Nagar', 
    '122': 'Sharda Puri', 
    '123': 'Kirti Nagar', 
    '124': 'Hari Nagar', 
    '125': 'Subhash Nagar', 
    '126': 'Mayapuri',
    '127': 'Mansarovar Garden', 
    '128': 'Janakpuri Garden'
}

In [68]:
is_west = df2['zone'] == 'West Zone'
df2.loc[is_west, 'ward'] = df2.loc[is_west, 'ward'].map(ward_names).fillna(df2['ward'])

In [69]:
df2[df2['zone'] == 'West Zone']['ward'].unique()

<StringArray>
[           'Aman Vihar',                'Kirari',          'Pratap Vihar',
      'Sultanpuri North',             'Jawalpuri',           'Nihal Vihar',
 'Guru Harikishan Nagar',        'Pashchim Vihar',            'Peeragarhi',
           'Nangloi Jat',     'Quammruddin Nagar',         'Chander Vihar',
             'Meerabagh',              'Keshopur',           'Tilak Nagar',
                'Khyala',         'Vishnu Garden',        'Rajouri Garden',
         'Tagore Garden',        'Raghubir Nagar',               'Madipur',
          'Punjabi Bagh',      'West Patel Nagar',      'East Patel Nagar',
          'Ranjit Nagar',             'Karampura',            'Moti Nagar',
          'Ramesh Nagar',           'Sharda Puri',           'Kirti Nagar',
            'Hari Nagar',         'Subhash Nagar',              'Mayapuri',
     'Mansarovar Garden',      'Janakpuri Garden']
Length: 35, dtype: str

In [70]:
df2[df2['zone'] == 'Najafgarh Zone']['ward'].unique()

<StringArray>
[ '5',  '6',  '7',  '8',  '9', '10', '11', '12', '13', '14', '15', '16', '17',
 '18', '19', '20', '70', '71', '72', '77', '78']
Length: 21, dtype: str

In [71]:
df2[df2['zone'] == 'Central-Zone']['ward'].unique()

<StringArray>
['209', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220',
 '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231',
 '232', '233', '234', '235', '236', '237', '238']
Length: 29, dtype: str

In [72]:
ward_names = {
    '209': 'Isapur', 
    '211': 'Dhansa', 
    '212': 'Mundka', 
    '213': 'Nilothi', 
    '214': 'Nangloi', 
    '215': 'Karala', 
    '216': 'Ladpur', 
    '217': 'Tikri Kalan', 
    '218': 'Jharoda Kalan', 
    '219': 'Kapashera', 
    '220': 'Bijwasan',
    '221': 'Mahipalpur', 
    '222': 'Raj Nagar', 
    '223': 'Palam', 
    '224': 'Sadh Nagar', 
    '225': 'Mahavir Enclave', 
    '226': 'Madhu Vihar', 
    '227': 'Manglapuri Extension', 
    '228': 'Dwarka Sector 3', 
    '229': 'Dwarka Sector 8', 
    '230': 'Nasirpur', 
    '231': 'Dashrath Puri',
    '232': 'Bindanpur', 
    '233': 'Jeewan Park', 
    '234': 'Uttam Nagar East', 
    '235': 'Mundka', 
    '236': 'Nilothi', 
    '237': 'Nangloi', 
    '238': 'Karala'
}

In [73]:
is_central = df2['zone'] == 'Central-Zone'
df2.loc[is_central, 'ward'] = df2.loc[is_central, 'ward'].map(ward_names).fillna(df2['ward'])

In [74]:
df2[df2['zone'] == 'Central-Zone']['ward'].unique()

<StringArray>
[              'Isapur',               'Dhansa',               'Mundka',
              'Nilothi',              'Nangloi',               'Karala',
               'Ladpur',          'Tikri Kalan',        'Jharoda Kalan',
            'Kapashera',             'Bijwasan',           'Mahipalpur',
            'Raj Nagar',                'Palam',           'Sadh Nagar',
      'Mahavir Enclave',          'Madhu Vihar', 'Manglapuri Extension',
      'Dwarka Sector 3',      'Dwarka Sector 8',             'Nasirpur',
        'Dashrath Puri',            'Bindanpur',          'Jeewan Park',
     'Uttam Nagar East']
Length: 25, dtype: str

In [75]:
df2[df2['zone'] == 'South Zone']['ward'].unique()

<StringArray>
[ '30',  '31',  '32',  '36', '119', '120', '129', '130', '131', '132', '133',
 '134', '135', '136', '137', '138', '139', '140', '141', '143', '144', '145',
 '146', '147', '148', '172']
Length: 26, dtype: str

In [76]:
ward_names = {
    '30': 'Janakpuri West',  
    '31': 'Nangal Raya',  
    '32': 'Hari Nagar A',  
    '36': 'Fateh Nagar', 
    '119': 'Mehrauli', 
    '120': 'Vasant Kunj', 
    '129': 'Kishangarh', 
    '130': 'Lado Sarai', 
    '131': 'Said-ul-Ajaib', 
    '132': 'Deoli', 
    '133': 'Tigri',
    '134': 'Sangam Vihar A', 
    '135': 'Sangam Vihar B', 
    '136': 'Sangam Vihar C', 
    '137': 'Sangam Vihar D', 
    '138': 'Sangam Vihar E', 
    '139': 'Khanpur', 
    '140': 'Ambedkar Nagar', 
    '141': 'Madangir', 
    '143': 'Pushp Vihar', 
    '144': 'Tughlakabad Extension', 
    '145': 'Tughlakabad',
    '146': 'Cherag Delhi', 
    '147': 'Shahpur Jat', 
    '148': 'Malviya Nagar', 
    '172': 'South Zone ward 1'
}

In [77]:
is_south = df2['zone'] == 'South Zone'
df2.loc[is_south, 'ward'] = df2.loc[is_south, 'ward'].map(ward_names).fillna(df2['ward'])

In [79]:
df2[df2['zone'] == 'South Zone']['ward'].unique()

<StringArray>
[       'Janakpuri West',           'Nangal Raya',          'Hari Nagar A',
           'Fateh Nagar',              'Mehrauli',           'Vasant Kunj',
            'Kishangarh',            'Lado Sarai',         'Said-ul-Ajaib',
                 'Deoli',                 'Tigri',        'Sangam Vihar A',
        'Sangam Vihar B',        'Sangam Vihar C',        'Sangam Vihar D',
        'Sangam Vihar E',               'Khanpur',        'Ambedkar Nagar',
              'Madangir',           'Pushp Vihar', 'Tughlakabad Extension',
           'Tughlakabad',          'Cherag Delhi',           'Shahpur Jat',
         'Malviya Nagar',     'South Zone ward 1']
Length: 26, dtype: str

In [80]:
df2[df2['zone'] == 'City-Sadar Paharganj(SP) Zone']['ward'].unique()

<StringArray>
['239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249',
 '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261',
 '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272']
Length: 33, dtype: str

In [81]:
ward_names = {
    '239': 'Hauz Khas', 
    '240': 'Safdarganj Enclave', 
    '241': 'Green Park', 
    '242': 'Munrika', 
    '243': 'RK Puram', 
    '244': 'Vasant Vihar', 
    '245': 'Greater Kailash', 
    '246': 'Chittaranjan Park', 
    '247': 'Alaknanda', 
    '248': 'Kalkaji', 
    '249': 'Govindpuri',
    '251': 'Harkesh Nagar', 
    '252': 'Okhla', 
    '253': 'Madanpur Khadar East', 
    '254': 'Madanpur Khadar West', 
    '255': 'Janakpuri East', 
    '256': 'Milap Nagar', 
    '257': 'Sitapuri', 
    '258': 'Roshanpura', 
    '259': 'Ladpur', 
    '260': 'Tikri Kalan', 
    '261': 'Jharoda Kalan',
    '262': 'Kapashera', 
    '263': 'Bijwasan', 
    '264': 'Mahipalpur', 
    '265': 'Raj Nagar', 
    '266': 'Palam', 
    '267': 'Sadh Nagar', 
    '268': 'Mahavir Enclave', 
    '269': 'Madhu Vihar', 
    '270': 'Manglapuri Extension', 
    '271': 'Dwarka Sector 3', 
    '272': 'Dwarka Sector 8'
}

In [83]:
is_sp = df2['zone'] == 'City-Sadar Paharganj(SP) Zone'
df2.loc[is_sp, 'ward'] = df2.loc[is_sp, 'ward'].map(ward_names).fillna(df2['ward'])

In [84]:
df2[df2['zone'] == 'City-Sadar Paharganj(SP) Zone']['ward'].unique()

<StringArray>
[           'Hauz Khas',   'Safdarganj Enclave',           'Green Park',
              'Munrika',             'RK Puram',         'Vasant Vihar',
      'Greater Kailash',    'Chittaranjan Park',            'Alaknanda',
              'Kalkaji',           'Govindpuri',        'Harkesh Nagar',
                'Okhla', 'Madanpur Khadar East', 'Madanpur Khadar West',
       'Janakpuri East',          'Milap Nagar',             'Sitapuri',
           'Roshanpura',               'Ladpur',          'Tikri Kalan',
        'Jharoda Kalan',            'Kapashera',             'Bijwasan',
           'Mahipalpur',            'Raj Nagar',                'Palam',
           'Sadh Nagar',      'Mahavir Enclave',          'Madhu Vihar',
 'Manglapuri Extension',      'Dwarka Sector 3',      'Dwarka Sector 8']
Length: 33, dtype: str

In [85]:
df2[df2['zone'] == 'Shahdara South Zone']['ward'].unique()

<StringArray>
['74', '91', '92', '93', '94', '95', '96', '149', '150', '151', '152']
Length: 11, dtype: str

In [86]:
ward_names = {
    '74': 'Andrews Ganj', 
    '91': 'Amar Colony', 
    '92': 'Kotla Mubarakpur', 
    '93': 'Defence Colony', 
    '94': 'Jangpura', 
    '95': 'Nizamuddin', 
    '96': 'Bhogal', 
    '149': 'Sidhartha Nagar', 
    '150': 'Lajpat Nagar East', 
    '151': 'Daryaganj', 
    '152': 'Bazar Sita Ram'
}

In [88]:
is_shahdara_south = df2['zone'] == 'Shahdara South Zone'
df2.loc[is_shahdara_south, 'ward'] = df2.loc[is_shahdara_south, 'ward'].map(ward_names).fillna(df2['ward'])

In [89]:
df2[df2['zone'] == 'Shahdara South Zone']['ward'].unique()

<StringArray>
[     'Andrews Ganj',       'Amar Colony',  'Kotla Mubarakpur',
    'Defence Colony',          'Jangpura',        'Nizamuddin',
            'Bhogal',   'Sidhartha Nagar', 'Lajpat Nagar East',
         'Daryaganj',    'Bazar Sita Ram']
Length: 11, dtype: str

In [90]:
df2[df2['zone'] == 'Keshav Puram Zone']['ward'].unique()

<StringArray>
['79', '80', '81', '82', '83', '84', '86', '153', '154']
Length: 9, dtype: str

In [91]:
ward_names = {
    '79': 'Vishwas Nagar', 
    '80': 'IP Extension', 
    '81': 'Preet Vihar', 
    '82': 'Patparganj', 
    '83': 'Mayur Vihar Phase1', 
    '84': 'Trilokpuri', 
    '86': 'New Ashok Nagar', 
    '153': 'Kalyanpuri', 
    '154': 'Khichripur'
}

In [92]:
is_keshavpuram = df2['zone'] == 'Keshav Puram Zone'
df2.loc[is_keshavpuram, 'ward'] = df2.loc[is_keshavpuram, 'ward'].map(ward_names).fillna(df2['ward'])

In [93]:
df2[df2['zone'] == 'Keshav Puram Zone']['ward'].unique()

<StringArray>
[     'Vishwas Nagar',       'IP Extension',        'Preet Vihar',
         'Patparganj', 'Mayur Vihar Phase1',         'Trilokpuri',
    'New Ashok Nagar',         'Kalyanpuri',         'Khichripur']
Length: 9, dtype: str

In [94]:
df2[df2['zone'] == 'Shahdara North Zone']['ward'].unique()

<StringArray>
['69', '73', '75', '76', '85', '87', '88', '89', '90']
Length: 9, dtype: str

In [95]:
df2 = df2.drop(df2[df2['zone'] == 'Shahdara North Zone'].index)

In [97]:
df2['zone'].unique()

array(['Narela Zone', 'Najafgarh Zone', 'Rohini Zone', 'South Zone',
       'West Zone', 'Shahdara South Zone', 'Keshav Puram Zone',
       'Karol Bagh Zone', 'Civil Lines Zone', 'Central-Zone',
       'City-Sadar Paharganj(SP) Zone'], dtype=object)

In [98]:
df2.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_Colony_Monthly_LST_2018_2025.csv')

In [111]:
df = df.drop(df[df['zone'] == 'Shahdara North Zone'].index)

In [113]:
df = df.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_NDVI_Monthly_From_2018-2025_with_ward_names.csv')

In [114]:
df = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_NDVI_Monthly_From_2018-2025_with_ward_names.csv')

In [115]:
df2 = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_Colony_Monthly_LST_2018_2025.csv')

In [116]:
merged_df = pd.merge(
    df, 
    df2, 
    on=['zone', 'ward', 'colony', 'year', 'month'], 
    how='inner', 
    suffixes=('_ndvi', '_lst')
)

In [117]:
merged_df.head()

,Unnamed: 0.1,Unnamed: 0_ndvi,zone,ward,colony,year,month,mean_ndvi,method,pixel_count_ndvi,valid_pixel_count_ndvi,cloud_pixel_percent,Unnamed: 0_lst,mean_lst_day_celsius,pixel_count_lst,valid_pixel_count_lst,invalid_pixel_percent
0,0,0,Narela Zone,Narela,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484,0,20.390259,3041,3041,0.000000
1,1,1,Narela Zone,Narela,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000,1,19.230675,242,242,0.000000
2,2,2,Narela Zone,Narela,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000,2,20.642038,1664,1664,0.000000
3,3,3,Narela Zone,Narela,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000,3,19.755209,1302,1301,0.076805
4,4,4,Narela Zone,Narela,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000,4,20.001610,2778,2729,1.763859

In [120]:
merged_df = merged_df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0_ndvi','Unnamed: 0_lst'])

In [121]:
merged_df.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_wardwise_lst_and_ndvi_2018_to_2025.csv')

In [122]:
df3 = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_wardwise_lst_and_ndvi_2018_to_2025.csv')

In [124]:
month_map = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12,
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
}

In [125]:
if merged_df['month'].dtype == 'object':
    merged_df['month_num'] = merged_df['month'].map(month_map)
else:
    merged_df['month_num'] = merged_df['month']

In [126]:
merged_df['temp_date'] = pd.to_datetime(
    merged_df['year'].astype(str) + '-' + merged_df['month_num'].astype(str).str.zfill(2) + '-01'
)

In [127]:
merged_df = merged_df.sort_values(by=['zone', 'ward', 'colony', 'temp_date']).reset_index(drop=True)

In [128]:
merged_df = merged_df.drop(columns=['month_num', 'temp_date'])

In [129]:
merged_df.head()

,zone,ward,colony,year,month,mean_ndvi,method,pixel_count_ndvi,valid_pixel_count_ndvi,cloud_pixel_percent,mean_lst_day_celsius,pixel_count_lst,valid_pixel_count_lst,invalid_pixel_percent
0,Central-Zone,Bijwasan,741,2018,1,0.090003,computed,1557.0,1557.0,0.0,21.874039,156,156,0.0
1,Central-Zone,Bijwasan,741,2018,2,0.100894,interpolated,1557.0,1557.0,0.0,25.035503,156,156,0.0
2,Central-Zone,Bijwasan,741,2018,3,0.111785,computed,1557.0,1557.0,0.0,33.572937,156,156,0.0
3,Central-Zone,Bijwasan,741,2018,4,0.116212,interpolated,1557.0,1557.0,0.0,44.439710,156,156,0.0
4,Central-Zone,Bijwasan,741,2018,5,0.120639,computed,1557.0,1557.0,0.0,44.807560,156,156,0.0

In [130]:
merged_df.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_wardwise_lst_and_ndvi_2018_to_2025.csv')