In [1]:
import pandas as pd
df = pd.read_csv('C:\\Users\\harsh\\Desktop\\isro hacakthon\\data\\raw\\Delhi_Colony_Monthly_NDVI_2018_2025.csv')

In [2]:
df.head()

,zone,ward,colony,year,month,mean_ndvi,method,pixel_count,valid_pixel_count,cloud_pixel_percent
0,7,1,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484
1,7,1,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000
2,7,1,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000
3,7,1,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000
4,7,1,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000

In [6]:
df['zone'].unique()

array([ 7,  6,  8,  9, 10, 11, 12,  5,  4,  3,  1,  2])

In [7]:
df['zone'] = df['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara North Zone', 12: 'Shahdara South Zone'}, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_972\2241085132.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['zone'] = df['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara North Zone', 12: 'Shahdara South Zone'}, inplace = True)

In [8]:
df.head()

,zone,ward,colony,year,month,mean_ndvi,method,pixel_count,valid_pixel_count,cloud_pixel_percent
0,Narela Zone,1,494,2018,1,0.286579,computed,27804.0,27711.0,0.334484
1,Narela Zone,1,513,2018,1,0.145620,computed,2288.0,2288.0,0.000000
2,Narela Zone,1,1059,2018,1,0.094268,computed,15275.0,15275.0,0.000000
3,Narela Zone,1,1060,2018,1,0.097503,computed,12066.0,12066.0,0.000000
4,Narela Zone,1,1102,2018,1,0.170267,computed,25548.0,25548.0,0.000000

In [10]:
df['zone'].unique()

array(['Narela Zone', 'Najafgarh Zone', 'Rohini Zone', 'South Zone',
       'West Zone', 'Shahdara North Zone', 'Shahdara South Zone',
       'Keshav Puram Zone', 'Karol Bagh Zone', 'Civil Lines Zone',
       'Central-Zone', 'City-Sadar Paharganj(SP) Zone'], dtype=object)

In [11]:
df[df['zone'] == 'Narela Zone']['ward'].unique()

array([ 1,  2,  3,  4, 27, 28, 29, 34])

In [13]:
df['ward'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  39,  40,
        41,  42,  43,  44,  45,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 143, 144, 145, 146, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
       161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
       174, 175, 176, 179, 180, 181, 183, 184, 185, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 251, 252, 253, 254, 255, 256, 257, 258,
       259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271,
       272])

In [27]:
df['ward'] = df['ward'].astype(str)

In [28]:
df['ward'].describe()

count     218880
unique       261
top          134
freq        3040
Name: ward, dtype: object

In [32]:
ward_names = {
    '1': 'Narela',
    '2': 'Bankner',
    '3': 'Holambi Kalan',
    '4': 'Alipur',
    '27': 'Begumpur',
    '28': 'Shahbad Dairy',
    '29': 'Pooth Khurd',
    '34': 'Nangloi'

}
is_narela = df['zone'] == 'Narela Zone'
df.loc[is_narela, 'ward'] = df.loc[is_narela, 'ward'].map(ward_names).fillna(df['ward'])

In [37]:
df[df['zone'] == 'Rohini Zone']['ward'].unique()

<StringArray>
['21', '22', '23', '24', '25', '26', '33', '35', '37', '39', '40', '45', '47',
 '48', '49', '50', '51', '52', '53', '54', '55', '56', '59', '60', '61', '62',
 '63', '64', '65', '66', '67', '68']
Length: 32, dtype: str

In [38]:
ward_names = {
    '21': 'Pooth Kalan',
    '22': 'Begumpur',
    '23': 'Shahbad Daulatpur',
    '24': 'Pitampura',
    '25': 'Saraswati Vihar',
    '26': 'Nimri Colony',
    '33': 'Wazirpur',
    '35': 'Ashok Vihar',
    '37': 'Tri Nagar',
    '39': 'Rampura',
    '40': 'Shakur Pur',
    '45': 'Sultanpuri A',
    '47': 'Sutanpuri B',
    '48': 'Sultanpuri C',
    '49': 'Sultanpuri East',
    '50': 'Sultanpur Majra',
    '51': 'Mangolpuri A',
    '52': 'Mangolpuri B',
    '53': 'Mangolpuri C',
    '54': 'Rohini Sector 21',
    '55': 'Rohini Sector 22',
    '56': 'Rohini Sector 23',
    '59': 'ward_a',
    '60': 'ward_b',
    '61': 'ward_c',
    '62': 'ward_d',
    '63': 'ward_e',
    '64': 'ward_f',
    '65': 'ward_g',
    '66': 'ward_h',
    '67': 'ward_i',
    '68': 'ward_j'
}
is_rohini = df['zone'] == 'Rohini Zone'
df.loc[is_rohini, 'ward'] = df.loc[is_rohini, 'ward'].map(ward_names).fillna(df['ward'])

In [40]:
df[df['zone'] == 'Rohini Zone']['ward'].unique()

<StringArray>
[      'Pooth Kalan',          'Begumpur', 'Shahbad Daulatpur',
         'Pitampura',   'Saraswati Vihar',      'Nimri Colony',
          'Wazirpur',       'Ashok Vihar',         'Tri Nagar',
           'Rampura',        'Shakur Pur',      'Sultanpuri A',
       'Sutanpuri B',      'Sultanpuri C',   'Sultanpuri East',
   'Sultanpur Majra',      'Mangolpuri A',      'Mangolpuri B',
      'Mangolpuri C',  'Rohini Sector 21',  'Rohini Sector 22',
  'Rohini Sector 23',            'ward_a',            'ward_b',
            'ward_c',            'ward_d',            'ward_e',
            'ward_f',            'ward_g',            'ward_h',
            'ward_i',            'ward_j']
Length: 32, dtype: str

In [42]:
df[df['zone'] == 'Civil Lines Zone']['ward'].unique()

<StringArray>
['161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171',
 '173', '174', '175', '176', '179', '180', '181', '183', '184', '189', '191']
Length: 22, dtype: str

In [43]:
ward_names = {
    '161': 'Burari',
    '162': 'Kadipur',
    '163': 'Mukundpur',
    '164': 'Sant Nagar', 
    '165': 'Jharoda', 
    '166': 'Bhalswa', 
    '167': 'Jahangirpuri', 
    '168': 'Samaypur Badli', 
    '169': 'Adarsh Nagar', 
    '170': 'Azadpur', 
    '171': 'Model Town',
    '173': 'Dhirpur', 
    '174': 'G.T.B Nagar', 
    '175': 'Vijay Nagar', 
    '176': 'Civil Lines', 
    '179': 'Malka Ganj', 
    '180': 'Timarpur', 
    '181': 'Mukherjee Nagar', 
    '183': 'Wazirabad', 
    '184': 'Majnu Ka Tila', 
    '189': 'Ward_1_civil_lines', 
    '191': 'Ward_2_civil_lines'
}
is_civil_lines = df['zone'] == 'Civil Lines Zone'
df.loc[is_civil_lines, 'ward'] = df.loc[is_civil_lines, 'ward'].map(ward_names).fillna(df['ward'])

In [46]:
df[df['zone'] == 'Karol Bagh Zone']['ward'].unique()

<StringArray>
['155', '156', '157', '158', '159', '160', '185', '188', '190', '192', '193',
 '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204',
 '205', '206', '207', '208']
Length: 26, dtype: str

In [47]:
ward_names = {
    '155': 'Rohini Central', 
    '156': 'Rohini North', 
    '157': 'Rohini South', 
    '158': 'Budh Vihar', 
    '159': 'Pooth Khurd', 
    '160': 'Bawana', 
    '185': 'Nangal Thakran', 
    '188': 'Kanjhawala', 
    '190': 'Rani Khera', 
    '192': 'Mubarakpur Dabas', 
    '193': 'Kirari Suleman Nagar',
    '194': 'Prem Nagar', 
    '195': 'Nithari', 
    '196': 'Karol_Bagh_ward_1', 
    '197': 'Karol_Bagh_ward_2', 
    '198': 'Karol_Bagh_ward_3', 
    '199': 'Karol_Bagh_ward_4', 
    '200': 'Karol_Bagh_ward_5', 
    '201': 'Karol_Bagh_ward_6', 
    '202': 'Karol_Bagh_ward_7', 
    '203': 'Karol_Bagh_ward_8', 
    '204': 'Karol_Bagh_ward_9',
    '205': 'Karol_Bagh_ward_10', 
    '206': 'Karol_Bagh_ward_11', 
    '207': 'Karol_Bagh_ward_12', 
    '208': 'Karol_Bagh_ward_13'
}

is_karol_bagh = df['zone'] == 'Karol Bagh Zone'
df.loc[is_karol_bagh, 'ward'] = df.loc[is_karol_bagh, 'ward'].map(ward_names).fillna(df['ward'])

In [49]:
df[df['zone'] == 'West Zone']['ward'].unique()

<StringArray>
[ '41',  '42',  '43',  '44',  '57',  '58',  '97',  '98',  '99', '100', '101',
 '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112',
 '113', '114', '115', '116', '117', '121', '122', '123', '124', '125', '126',
 '127', '128']
Length: 35, dtype: str

In [50]:
ward_names = {
    '41': 'Aman Vihar',  
    '42': 'Kirari',  
    '43': 'Pratap Vihar',  
    '44': 'Sultanpuri North',  
    '57': 'Jawalpuri',  
    '58': 'Nihal Vihar',  
    '97': 'Guru Harikishan Nagar',  
    '98': 'Pashchim Vihar',  
    '99': 'Peeragarhi', 
    '100': 'Nangloi Jat', 
    '101': 'Quammruddin Nagar',
    '102': 'Chander Vihar', 
    '103': 'Meerabagh', 
    '104': 'Keshopur', 
    '105': 'Tilak Nagar', 
    '106': 'Khyala', 
    '107': 'Vishnu Garden', 
    '108': 'Rajouri Garden', 
    '109': 'Tagore Garden', 
    '110': 'Raghubir Nagar', 
    '111': 'Madipur', 
    '112': 'Punjabi Bagh',
    '113': 'West Patel Nagar', 
    '114': 'East Patel Nagar', 
    '115': 'Ranjit Nagar', 
    '116': 'Karampura', 
    '117': 'Moti Nagar', 
    '121': 'Ramesh Nagar', 
    '122': 'Sharda Puri', 
    '123': 'Kirti Nagar', 
    '124': 'Hari Nagar', 
    '125': 'Subhash Nagar', 
    '126': 'Mayapuri',
    '127': 'Mansarovar Garden', 
    '128': 'Janakpuri Garden'
}
is_west = df['zone'] == 'West Zone'
df.loc[is_west, 'ward'] = df.loc[is_west, 'ward'].map(ward_names).fillna(df['ward'])

In [52]:
df[df['zone'] == 'Najafgarh Zone']['ward'].unique()

<StringArray>
[    'Bakhtawapur',          'Burari',         'Kadipur',       'Mukundpur',
      'Sant Nagar',         'Jharoda',         'Bhalswa',    'Jahangirpuri',
  'Samaypur Badli',    'Adarsh Nagar',         'Azadpur',      'Model Town',
         'Dhirpur',    'G.T.B. Nagar',     'Vijay Nagar',     'Civil Lines',
      'Malka Ganj',        'Timarpur', 'Mukherjee Nagar',       'Wazirabad',
   'Majnu ka Tila']
Length: 21, dtype: str

In [53]:
ward_names = {
    'Bakhtawapur': 'Dabri',          
    'Burari': 'Sagarpur',         
    'Kadipur': 'Manglapuri',       
    'Mukundpur': 'Dwarka A',
    'Sant Nagar': 'Dwarka B',         
    'Jharoda': 'Dwarka C',         
    'Bhalswa': 'Nawada',    
    'Jahangirpuri': 'Uttam Nagar',
    'Samaypur Badli': 'Bindra Pur',    
    'Adarsh Nagar': 'Matiala',         
    'Azadpur': 'Mohan Garden',      
    'Model Town': 'Hastal',
    'Dhirpur': 'Vikas Puri',    
    'G.T.B. Nagar': 'Kunwar Singh Nagar',     
    'Vijay Nagar': 'Chander Vihar Extension',     
    'Civil Lines': 'Baprola',
    'Malka Ganj': 'Sainik Enclave',        
    'Timarpur': 'Nangli Sakrawati', 
    'Mukherjee Nagar': 'Kakrola',       
    'Wazirabad': 'Najafgarh',
    'Majnu ka Tila': 'Dichaon Kalan'
}
is_najafgarh = df['zone'] == 'Najafgarh Zone'
df.loc[is_najafgarh, 'ward'] = df.loc[is_najafgarh, 'ward'].map(ward_names).fillna(df['ward'])

In [56]:
df[df['zone'] == 'Central-Zone']['ward'].unique()

<StringArray>
['209', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220',
 '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231',
 '232', '233', '234', '235', '236', '237', '238']
Length: 29, dtype: str

In [57]:
ward_names = {
    '209': 'Isapur', 
    '211': 'Dhansa', 
    '212': 'Mundka', 
    '213': 'Nilothi', 
    '214': 'Nangloi', 
    '215': 'Karala', 
    '216': 'Ladpur', 
    '217': 'Tikri Kalan', 
    '218': 'Jharoda Kalan', 
    '219': 'Kapashera', 
    '220': 'Bijwasan',
    '221': 'Mahipalpur', 
    '222': 'Raj Nagar', 
    '223': 'Palam', 
    '224': 'Sadh Nagar', 
    '225': 'Mahavir Enclave', 
    '226': 'Madhu Vihar', 
    '227': 'Manglapuri Extension', 
    '228': 'Dwarka Sector 3', 
    '229': 'Dwarka Sector 8', 
    '230': 'Nasirpur', 
    '231': 'Dashrath Puri',
    '232': 'Bindanpur', 
    '233': 'Jeewan Park', 
    '234': 'Uttam Nagar East', 
    '235': 'Mundka', 
    '236': 'Nilothi', 
    '237': 'Nangloi', 
    '238': 'Karala'
}
is_central = df['zone'] == 'Central-Zone'
df.loc[is_central, 'ward'] = df.loc[is_central, 'ward'].map(ward_names).fillna(df['ward'])

In [61]:
df[df['zone'] == 'South Zone']['ward'].unique()

<StringArray>
[ '30',  '31',  '32',  '36', '119', '120', '129', '130', '131', '132', '133',
 '134', '135', '136', '137', '138', '139', '140', '141', '143', '144', '145',
 '146', '147', '148', '172']
Length: 26, dtype: str

In [62]:
ward_names = {
    '30': 'Janakpuri West',  
    '31': 'Nangal Raya',  
    '32': 'Hari Nagar A',  
    '36': 'Fateh Nagar', 
    '119': 'Mehrauli', 
    '120': 'Vasant Kunj', 
    '129': 'Kishangarh', 
    '130': 'Lado Sarai', 
    '131': 'Said-ul-Ajaib', 
    '132': 'Deoli', 
    '133': 'Tigri',
    '134': 'Sangam Vihar A', 
    '135': 'Sangam Vihar B', 
    '136': 'Sangam Vihar C', 
    '137': 'Sangam Vihar D', 
    '138': 'Sangam Vihar E', 
    '139': 'Khanpur', 
    '140': 'Ambedkar Nagar', 
    '141': 'Madangir', 
    '143': 'Pushp Vihar', 
    '144': 'Tughlakabad Extension', 
    '145': 'Tughlakabad',
    '146': 'Cherag Delhi', 
    '147': 'Shahpur Jat', 
    '148': 'Malviya Nagar', 
    '172': 'South Zone ward 1'
}
is_south = df['zone'] == 'South Zone'
df.loc[is_south, 'ward'] = df.loc[is_south, 'ward'].map(ward_names).fillna(df['ward'])

In [65]:
df[df['zone'] == 'City-Sadar Paharganj(SP) Zone']['ward'].unique()

<StringArray>
['239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249',
 '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261',
 '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272']
Length: 33, dtype: str

In [66]:
ward_names = {
    '239': 'Hauz Khas', 
    '240': 'Safdarganj Enclave', 
    '241': 'Green Park', 
    '242': 'Munrika', 
    '243': 'RK Puram', 
    '244': 'Vasant Vihar', 
    '245': 'Greater Kailash', 
    '246': 'Chittaranjan Park', 
    '247': 'Alaknanda', 
    '248': 'Kalkaji', 
    '249': 'Govindpuri',
    '251': 'Harkesh Nagar', 
    '252': 'Okhla', 
    '253': 'Madanpur Khadar East', 
    '254': 'Madanpur Khadar West', 
    '255': 'Janakpuri East', 
    '256': 'Milap Nagar', 
    '257': 'Sitapuri', 
    '258': 'Roshanpura', 
    '259': 'Ladpur', 
    '260': 'Tikri Kalan', 
    '261': 'Jharoda Kalan',
    '262': 'Kapashera', 
    '263': 'Bijwasan', 
    '264': 'Mahipalpur', 
    '265': 'Raj Nagar', 
    '266': 'Palam', 
    '267': 'Sadh Nagar', 
    '268': 'Mahavir Enclave', 
    '269': 'Madhu Vihar', 
    '270': 'Manglapuri Extension', 
    '271': 'Dwarka Sector 3', 
    '272': 'Dwarka Sector 8'
}
is_sp = df['zone'] == 'City-Sadar Paharganj(SP) Zone'
df.loc[is_sp, 'ward'] = df.loc[is_sp, 'ward'].map(ward_names).fillna(df['ward'])

In [82]:
df[df['zone'] == 'Shahdara South Zone']['ward'].unique()

<StringArray>
[     'Andrews Ganj',       'Amar Colony',  'Kotla Mubarakpur',
    'Defence Colony',          'Jangpura',        'Nizamuddin',
            'Bhogal',   'Sidhartha Nagar', 'Lajpat Nagar East',
         'Daryaganj',    'Bazar Sita Ram']
Length: 11, dtype: str

In [83]:
ward_names = {
    '74': 'Andrews Ganj', 
    '91': 'Amar Colony', 
    '92': 'Kotla Mubarakpur', 
    '93': 'Defence Colony', 
    '94': 'Jangpura', 
    '95': 'Nizamuddin', 
    '96': 'Bhogal', 
    '149': 'Sidhartha Nagar', 
    '150': 'Lajpat Nagar East', 
    '151': 'Daryaganj', 
    '152': 'Bazar Sita Ram'
}

is_shahdara_south = df['zone'] == 'Shahdara South Zone'
df.loc[is_shahdara_south, 'ward'] = df.loc[is_shahdara_south, 'ward'].map(ward_names).fillna(df['ward'])

In [84]:
df[df['zone'] == 'Shahdara North Zone']['ward'].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [85]:
ward_names = {
    '69': 'Than Singh Nagar', 
    '73': 'Kishan Ganj', 
    '75': 'Padam Nagar', 
    '76': 'Shashtri Nagar', 
    '85': 'Sadar Bazar', 
    '87': 'Deputy Ganj', 
    '88': 'Kadam Sharif', 
    '89': 'Qasabpura', 
    '90': 'Anand Vihar'
}
is_shahdara_north = df['zone'] == 'Shahdara North Zone'
df.loc[is_shahdara_north, 'ward'] = df.loc[is_shahdara_north, 'ward'].map(ward_names).fillna(df['ward'])

In [86]:
df[df['zone'] == 'Shahdara North Zone']['ward'].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [87]:
df['zone'].unique()

array(['Narela Zone', 'Najafgarh Zone', 'Rohini Zone', 'South Zone',
       'West Zone', 'Shahdara North Zone', 'Shahdara South Zone',
       'Keshav Puram Zone', 'Karol Bagh Zone', 'Civil Lines Zone',
       'Central-Zone', 'City-Sadar Paharganj(SP) Zone'], dtype=object)

In [88]:
df[df['zone'] == 'Keshav Puram Zone']['ward'].unique()

<StringArray>
['79', '80', '81', '82', '83', '84', '86', '153', '154']
Length: 9, dtype: str

In [89]:
ward_names = {
    '79': 'Vishwas Nagar', 
    '80': 'IP Extension', 
    '81': 'Preet Vihar', 
    '82': 'Patparganj', 
    '83': 'Mayur Vihar Phase1', 
    '84': 'Trilokpuri', 
    '86': 'New Ashok Nagar', 
    '153': 'Kalyanpuri', 
    '154': 'Khichripur'
}
is_keshavpuram = df['zone'] == 'Keshav Puram Zone'
df.loc[is_keshavpuram, 'ward'] = df.loc[is_keshavpuram, 'ward'].map(ward_names).fillna(df['ward'])

In [90]:
df[df['zone'] == 'Keshav Puram Zone']['ward'].unique()

<StringArray>
[     'Vishwas Nagar',       'IP Extension',        'Preet Vihar',
         'Patparganj', 'Mayur Vihar Phase1',         'Trilokpuri',
    'New Ashok Nagar',         'Kalyanpuri',         'Khichripur']
Length: 9, dtype: str

In [95]:
df.to_csv('C:\\Users\\harsh\\Desktop\\isro hacakthon\\data\\raw\\Delhi_NDVI_Monthly_From_2018-2025_with_ward_names.csv')

In [96]:
df2 = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_NDVI_Monthly_From_2018-2025_with_ward_names.csv')